### PR TITLE
Adding Creator Module and UI Changes

### PR DESCRIPTION
**Pull request by subhed**

### CODE REVIEW

**Comment by kbuffardi** [comment]
@subhed some of these changes are overwriting patches I made (particularly to the .erb headers) that include the fixed branding (`Codewit` instead of `CodeWidUs`) and the security measure #15

Please resolve those changes back to merge with **primary**

**Comment by subhed** [comment]
FIXED

**Comment by kbuffardi** [comment]
This PR still overwrites the security patch made in this commit: https://github.com/kbuffardi/CodeWitUs/commit/c5595bd2232c4b6634c0084ce326abab20298c4e

**Comment by subhed** [comment]
I'll close this PR and make new one.

**Pull request closed without merging**
